// Code generated by "stringer -type=sectionType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[sectionStart-0]
	_ = x[sectionVideo-1]
	_ = x[sectionAudio-2]
}

const _sectionType_name = "sectionStartsectionVideosectionAudio"

var _sectionType_index = [...]uint8{0, 12, 24, 36}

func (i sectionType) String() string {
	if i < 0 || i >= sectionType(len(_sectionType_index)-1) {
		return "sectionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _sectionType_name[_sectionType_index[i]:_sectionType_index[i+1]]
}
